from src.models.project import Project, Post, Task, DenormUser, TaskStatusEnum, ProjectStatusEnum, ProjectRoleEnum
from src.services.protocols import ProjectRepository, ProjectKafkaProducer
import src.services.errors as project_errors
import src.adapters.repository.errors as adapter_errors
import uuid


class ProjectService():
    def __init__(
        self,
        project_repository: ProjectRepository,
        kafka_producer: ProjectKafkaProducer
    ) -> None:
        self._project_repository = project_repository
        self._kafka_producer = kafka_producer

    async def create_project(self, project: Project) -> None: ...
    async def update_project(self, project: Project) -> None: ...
    async def get_project_info(self, id: uuid.UUID) -> Project: ...
    async def get_project_statistics(self, id: uuid.UUID) -> list[int]: ...
    async def get_projects(self, ids: list[id]) -> list[Project]: ...

    async def create_task(self, task: Task) -> None: ...
    async def update_task(self, task: Task) -> None: ...
    async def get_project_tasks(self, id: uuid.UUID) -> list[Task]: ...

    async def create_post(self, post: Post) -> None: ...
    async def update_post(self, post: Post) -> None: ...
    async def delete_post(self, id: uuid.UUID) -> None: ...
    async def get_project_posts(self, id: uuid.UUID) -> list[Post]: ...

    async def get_user_memberships() -> list[uuid.UUID]: ...
    async def add_member(self, user: DenormUser) -> None: ...
    async def remove_member(self, id: uuid.UUID) -> None: ...
