from typing import Protocol
from src.models.project import Project, Post, Task, Tag, DenormUser
from uuid import UUID


class ProjectRepository(Protocol):
    async def create_project(self, project: Project) -> UUID: ...
    async def get_project_info(self, id: UUID) -> Project: ...
    async def get_project_statistics(self, id: UUID) -> dict: ...
    async def get_projects(self, ids: list[id]) -> list[Project]: ...
    async def update_project(self, project: Project) -> None: ...

    async def create_task(self, task: Task) -> UUID: ...
    async def update_task(self, task: Task) -> None: ...
    async def get_project_tasks(self, id: UUID) -> list[Task]: ...

    async def create_post(self, post: Post) -> UUID: ...
    async def update_post(self, post: Post) -> None: ...
    async def delete_post(self, id: UUID) -> None: ...
    async def get_project_posts(self, id: UUID) -> list[Post]: ...

    async def get_user_memberships(
        self, user_id: UUID) -> list[list[UUID]]: ...

    async def add_member(self, project_id: UUID, user: DenormUser) -> None: ...
    async def remove_member(self, id: UUID) -> None: ...


class ProjectKafkaProducer(Protocol):
    async def send_create_project(self, project: Project) -> None: ...
    async def send_update_project(self, project: Project) -> None: ...
    async def send_create_post(self, post: Post) -> None: ...
    async def send_update_post(self, post: Post) -> None: ...
    async def send_delete_post(self, id: UUID) -> None: ...
