from uuid import UUID
import psycopg_pool
from src.models.project import Project, Post, Task, DenormUser, Tag


class ProjectPostgresRepository:
    def __init__(self, pool: psycopg_pool.AsyncConnectionPool) -> None:
        self._pool = pool

    async def create_project(self, project: Project) -> UUID:
        ...

    async def get_project_info(self, id: UUID) -> Project: ...
    async def get_project_statistics(self, id: UUID) -> list[int]: ...
    async def get_projects(self, ids: list[id]) -> list[Project]: ...

    async def add_tags(self, project_id: UUID, tags: list[Tag]) -> None: ...
    async def remove_tags(self, project_id: UUID, tags: list[Tag]) -> None: ...
    async def update_project(self, project: Project) -> None: ...

    async def add_tags_to_project_connection(
        self, project_id: UUID, tags: list[Tag]
    ) -> None: ...
    async def remove_tags_from_project_connection(
        self, project_id: UUID, tags: list[Tag]) -> None: ...

    async def create_task(self, task: Task) -> UUID: ...
    async def update_task(self, task: Task) -> None: ...
    async def get_project_tasks(self, id: UUID) -> list[Task]: ...

    async def create_post(self, post: Post) -> UUID: ...
    async def update_post(self, post: Post) -> None: ...
    async def delete_post(self, id: UUID) -> None: ...
    async def get_project_posts(self, id: UUID) -> list[Post]: ...

    async def get_user_memberships(
        self, user_id: UUID) -> list[list[UUID]]: ...

    async def add_member(self, progect_id: UUID, user: DenormUser) -> None: ...
    async def remove_member(self, id: UUID) -> None: ...

    async def add_user_to_project_connection(
        self, project_id: UUID, user_id: UUID) -> None: ...

    async def remove_user_from_project_connection(
        self, project_id: UUID, user_id: UUID) -> None: ...
