import uuid
import psycopg_pool
from src.models.project import Project, Post, Task, DenormUser


class ProjectPostgresRepository:
    def __init__(self, pool: psycopg_pool.AsyncConnectionPool) -> None:
        self._pool = pool

    async def create_project(self, project: Project) -> None: ...
    async def update_project(self, project: Project) -> None: ...
    async def get_project_info(self, id: uuid.UUID) -> Project: ...
    async def get_project_statistics(self, id: uuid.UUID) -> list[int]: ...
    async def get_projects(self, ids: list[id]) -> list[Project]: ...

    async def create_task(self, task: Task) -> None: ...
    async def update_task(self, task: Task) -> None: ...
    async def get_project_tasks(self, id: uuid.UUID) -> list[Task]: ...

    async def create_post(self, post: Post) -> None: ...
    async def update_post(self, post: Post) -> None: ...
    async def delete_post(self, id: uuid.UUID) -> None: ...
    async def get_project_posts(self, id: uuid.UUID) -> list[Post]: ...

    async def get_user_memberships() -> list[uuid.UUID]: ...
    async def add_member(self, user: DenormUser) -> None: ...
    async def remove_member(self, id: uuid.UUID) -> None: ...
