from aiokafka import AIOKafkaProducer
from src.models.project import Project, Post


class KafkaProducerClient:
    def __init__(self, producer: AIOKafkaProducer) -> None: ...

    def send_create_project(self, project: Project) -> None: ...

    def send_update_project(self, project: Project) -> None: ...

    def send_create_post(self, post: Post) -> None: ...

    def send_update_post(self, post: Post) -> None: ...

    def send_delete_post(self, id: str) -> None: ...
